### ISSUE TITLE
Account ID is not returned in extra info

### ISSUE THREAD

**Issue by ryanwood** [jbynum/omniauth-emma#1]
[FYI - I'm in the Emma OAuth beta]

You need the accountID in order to make API calls yet that field is not present in the extra info returned by this gem.

**Comment by jbynum** [comment]
@ryanwood sorry about that. I just pushed a new gem version that should solve that problem. The account ids should be in the info hash and in the raw info.

**Comment by ryanwood** [comment]
Thanks man. Much appreciated.
